INSERT INTO itineraries (itineraryid, name, city, country, languages, tags, events, postid, username, creationdate, lastupdate) VALUES
(1, 'Discover NYC', 'New York', 'USA', ARRAY['English', 'Spanish'], ARRAY['sightseeing', 'food'], ARRAY['event1', 'event2'], 101, 'user1', NOW(), NOW()),
(2, 'Beach Day LA', 'Los Angeles', 'USA', ARRAY['English'], ARRAY['beach', 'surfing'], ARRAY['event3', 'event4'], 102, 'user2', NOW(), NOW()),
(3, 'Tokyo Adventure', 'Tokyo', 'Japan', ARRAY['Japanese', 'English'], ARRAY['shopping', 'nightlife'], ARRAY['event5', 'event6'], 103, 'user3', NOW(), NOW()),
(4, 'Historical London', 'London', 'UK', ARRAY['English'], ARRAY['history', 'museum'], ARRAY['event7'], 104, 'user4', NOW(), NOW()),
(5, 'Sydney Exploration', 'Sydney', 'Australia', ARRAY['English'], ARRAY['beach', 'opera'], ARRAY['event8', 'event9'], 105, 'user1', NOW(), NOW()),
(6, 'New York Art Tour', 'New York', 'USA', ARRAY['English'], ARRAY['art', 'gallery'], ARRAY['event10'], 106, 'user2', NOW(), NOW()),
(7, 'Cultural Experience LA', 'Los Angeles', 'USA', ARRAY['English', 'Spanish'], ARRAY['culture', 'food'], ARRAY['event11'], 107, 'user5', NOW(), NOW()),
(8, 'Paris Getaway', 'Paris', 'France', ARRAY['French', 'English'], ARRAY['romantic', 'food'], ARRAY['event12', 'event13'], 108, 'user3', NOW(), NOW()),
(9, 'Tokyo Food Tour', 'Tokyo', 'Japan', ARRAY['Japanese', 'English'], ARRAY['food', 'sushi'], ARRAY['event14'], 109, 'user1', NOW(), NOW()),
(10, 'Melbourne Weekend', 'Melbourne', 'Australia', ARRAY['English'], ARRAY['sports', 'coffee'], ARRAY['event15'], 110, 'user6', NOW(), NOW()),
(11, 'Paris Fashion Week', 'Paris', 'France', ARRAY['French'], ARRAY['fashion', 'luxury'], ARRAY['event16'], 111, 'user4', NOW(), NOW()),
(12, 'London Music Festival', 'London', 'UK', ARRAY['English'], ARRAY['music', 'festival'], ARRAY['event17', 'event18'], 112, 'user5', NOW(), NOW()),
(13, 'Hiking Adventure', 'Vancouver', 'Canada', ARRAY['English'], ARRAY['hiking', 'nature'], ARRAY['event19'], 113, 'user2', NOW(), NOW()),
(14, 'Tech Conference', 'San Francisco', 'USA', ARRAY['English'], ARRAY['tech', 'innovation'], ARRAY['event20'], 114, 'user3', NOW(), NOW()),
(15, 'Tokyo Nightlife', 'Tokyo', 'Japan', ARRAY['Japanese', 'English'], ARRAY['nightlife', 'club'], ARRAY['event21', 'event22'], 115, 'user1', NOW(), NOW());